<TopBarWidget>:

    MDTopAppBarLeadingButtonContainer:

        MDActionTopAppBarButton:
            id: back_btn
            icon: root.back_button_icon
            on_press: root._on_back(self)


    MDTopAppBarTitle:
        id: track_name_label
        text: "No track playing"
        halign: "center"

    MDTopAppBarTrailingButtonContainer:

        MDActionTopAppBarButton:
            id: device_btn
            icon: "cast"
            on_press: root._on_device_button_press(self)
